type User @table {
  uid: String!
  email: String!
  createdAt: Timestamp!
  displayName: String
  phoneNumber: String
}

type MenuItem @table {
  name: String!
  price: Float!
  description: String!
  imageUrl: String!
  createdAt: Timestamp!
  category: String
  isAvailable: Boolean
}

type Order @table {
  user: User!
  totalPrice: Float!
  orderStatus: String!
  createdAt: Timestamp!
  deliveryAddress: String
  notes: String
}

type OrderItem @table {
  order: Order!
  menuItem: MenuItem!
  quantity: Int!
  itemPrice: Float!
}